export const dashboardConfig = {
  ADMIN: {
    showStats: true,
    stats: [
      { icon: "👥", value: "students", label: "Students" },
      { icon: "✉️", value: "faculty", label: "Faculty" },
      { icon: "💼", value: "courses", label: "Courses" },
    ],
    modules: [
      {
        title: "Attendance",
        description: "Manage student attendance records.",
        image: "attendance.png",
        buttonText: "Manage Attendance",
        path: "/admin/attendance",
      },
      {
        title: "Fees",
        description: "Track and manage student fees.",
        image: "fees.png",
        buttonText: "Manage Fees",
        path: "/admin/fees",
      },
      {
        title: "Students",
        description: "Oversee and manage student records ",
        image: "student.png",
        buttonText: "Manage Students",
        path: "/admin/student",
      },
      {
        title: "Faculty",
        description: "Oversee and manage Faculty records ",
        image: "faculty.png",
        buttonText: "Manage Faculty",
        path: "/admin/faculty",
      },

      {
        title: "Events",
        description: "Manage college events.",
        image: "events.png",
        buttonText: "Manage Events",
        path: "/events",
      },
      {
        title: "Announcement",
        description: " create and manage Announcements.",
        image: "announcement.png",
        buttonText: "Open Announcement",
        path: "/announcement",
      },
      {
        title: "Letters & Application",
        description: "Oversee applications requests ",
        image: "application.png",
        buttonText: "Manage Applications",
        path: "/admin/application",
      },
    ],
  },

  FACULTY: {
    showStats: false,
    modules: [
      {
        title: "Attendance",
        description: "Mark and view attendance .",
        image: "attendance.png",
        buttonText: "Open Attendance",
        path: "/faculty/attendance/*",
      },
      {
        title: "Notes",
        description: "Upload and manage study notes.",
        image: "notes.png",
        buttonText: "Manage Notes",
        path: "/faculty/notes",
      },
      {
        title: "Assignments",
        description: "Create and review assignments.",
        image: "assignments.png",
        buttonText: "View Assignments",
        path: "/faculty/assignments",
      },
      {
        title: "Events",
        description: "Manage college events.",
        image: "events.png",
        buttonText: "Manage Events",
        path: "/events",
      },
      {
        title: "Exams",
        description: "Manage class tests and exams.",
        image: "exams.png",
        buttonText: "Manage Exams",
        path: "/faculty/exams",
      },
      {
        title: "Announcement",
        description: " create and manage Announcements.",
        image: "announcement.png",
        buttonText: "Open Announcement",
        path: "/announcement",
      },
      {
        title: "Notifications",
        description: "View important notifications.",
        image: "notifications.png",
        buttonText: "View Notifications",
        path: "/faculty/notifications",
      },
       {
        title: "Messenger",
        description: " send and read messages.",
        image: "messenger.png",
        buttonText: "open messenger",
        path: "/messenger",
      },
      {
        title: "Letters & Application",
        description: "Oversee Applications requests ",
        image: "application.png",
        buttonText: "Manage Applications",
        path: "/faculty/application",
      },
    ],
  },

  STUDENT: {
    showStats: false,
    modules: [
      {
        title: "Attendance",
        description: "View your attendance records.",
        image: "attendance.png",
        buttonText: "View Attendance",
        path: "/student/attendance",
      },
     
      {
        title: "Fees",
        description: "View and pay your fees.",
        image: "fees.png",
        buttonText: "View Fees",
        path: "/student/fees",
      },
     
      {
        title: "Online Test",
        description: "access and complete class test.",
        image: "class-test.png",
        buttonText: "Quiz",
        path: "/student/class-test",
      },
       {
        title: "Assignments",
        description: "Access and Submit assignments.",
        image: "assignments.png",
        buttonText: "View Assignments",
        path: "/student/assignments",
      },
       {
        title: "Notes",
        description: "Access subject-wise notes.",
        image: "notes.png",
        buttonText: "View Notes",
        path: "/student/notes",
      },
      {
        title: "Events",
        description: "view college events.",
        image: "events.png",
        buttonText: "view Events",
        path: "/events",
      },
       
      {
        title: "Announcement",
        description: " create and manage Announcements.",
        image: "announcement.png",
        buttonText: "Open Announcement",
        path: "/announcement",
      },
      {
        title: "Letters & Application",
        description: "Send Applications/Letters ",
        image: "application.png",
        buttonText: " Applications",
        path: "/student/application",
      },
      {
        title: "Exams",
        description: "Check exams and results.",
        image: "exams.png",
        buttonText: "View Exams",
        path: "/student/exams",
      },
      {
        title: "Messenger",
        description: " send and read messages.",
        image: "messenger.png",
        buttonText: "open messenger",
        path: "/messenger",
      },
    ],
  },
};
